config/routes.rb
Rails.application.routes.draw do
  root 'concepts#home'

  resources :concepts do
    resources :tips
  end
  resources :votes

  post 'signup', to: 'session#signup'
  post 'signin', to: 'session#signin'
  delete 'signout', to: 'session#signout'

end

app/models/concept.rb
# == Schema Information
#
# Table name: concepts
#
#  id         :integer          not null, primary key
#  concept    :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Concept < ActiveRecord::Base
  has_many :tips

end

app/controllers/concepts_controller.rb
class ConceptsController < ApplicationController
  before_action :set_concept, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate, only: [ :home]


  # GET /concepts
  # GET /concepts.json

  def home
    @tile_colors = ['lt-blue', 'red', 'purple', 'grey', 'gold', 'green', 'lt-blue', 'lt-gold', 'green', 'gold', 'blue', 'lt-gold',
                   'lt-blue', 'red', 'purple', 'grey', 'gold', 'red', 'lt-blue', 'lt-gold', 'gold', 'purple', 'grey', 'red']

    @concepts = Concept.all
  end

  def index
    @concepts = Concept.all
  end

  # GET /concepts/1
  # GET /concepts/1.json
  def show
    @tips = @concept.tips.order('created_at DESC')
    # @concept = Tip.where('concept_id = ?', 193).order('created_at desc')
    # @concept.tips = @concept.tips.group_by { |t| t.posted_at. }
    #
    #
    # @concept.tips.all
  end

  # GET /concepts/new
  def new
    @concept = Concept.new
  end

  # GET /concepts/1/edit
  def edit
  end

  # POST /concepts
  # POST /concepts.json
  def create
    @concept = Concept.new(concept_params)

    respond_to do |format|
      if @concept.save
        format.html { redirect_to @concept, notice: 'Concept was successfully created.' }
        format.json { render :show, status: :created, location: @concept }
      else
        format.html { render :new }
        format.json { render json: @concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /concepts/1
  # PATCH/PUT /concepts/1.json
  def update
    respond_to do |format|
      if @concept.update(concept_params)
        format.html { redirect_to @concept, notice: 'Concept was successfully updated.' }
        format.json { render :show, status: :ok, location: @concept }
      else
        format.html { render :edit }
        format.json { render json: @concept.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /concepts/1
  # DELETE /concepts/1.json
  def destroy
    @concept.destroy
    respond_to do |format|
      format.html { redirect_to concepts_url, notice: 'Concept was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_concept
      @concept = Concept.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def concept_params
      params[:concept]
    end
end

app/helpers/concepts_helper.rb
module ConceptsHelper
end

app/views/concepts/_form.html.erb
<%= form_for(@concept) do |f| %>
  <% if @concept.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@concept.errors.count, "error") %> prohibited this concept from being saved:</h2>

      <ul>
      <% @concept.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/concepts/_tiles.html.erb
<div class="container">

  <div class="row">

    <div class="col-lg-12">
      <h1 class="page-header"></h1>
    </div>
    <% @concepts.each_with_index do | conc, x | %>
        <div class="col-lg-3 col-md-4 col-xs-6 thumb">
            <%= link_to concept_path(conc), class: "thumbnail thumb #{conc.concept.gsub(/\s/,'-')}" do %>
                <h1><%= conc.concept %></h1>
            <% end %>
        </div>
    <% end %>
  </div>
</div>

app/views/concepts/edit.html.erb
<h1>Editing concept</h1>

<%= render 'form' %>

<%= link_to 'Show', @concept %> |
<%= link_to 'Back', concepts_path %>

app/views/concepts/home.html.erb
<div class="jumbotron" id="jumbotron-image">
  <div class="container push-spaces">


    <div class="panel panel-primary panel-transparent">
      <div class="panel-body">
        <h2><div class="body-text"> Immersive boot camps are extremely difficult! <br>However, those who participate in them experience very similar challenges and successes.  With the learnatizer we can now organize our growing pains and joys by category, in order to collaborate with others.
      </div></h2>
      </div>
    </div>

  </div>
</div>

<div class="directive"><h1 class="text-center">Choose the concept below that interests you</h1>

</div>
  <%= render 'concepts/tiles' %>

app/views/concepts/index.html.erb
<h1>Listing concepts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @concepts.each do |concept| %>
      <tr>
        <td><%= link_to 'Show', concept %></td>
        <td><%= link_to 'Edit', edit_concept_path(concept) %></td>
        <td><%= link_to 'Destroy', concept, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Concept', new_concept_path %>

app/views/concepts/new.html.erb
<h1>New concept</h1>

<%= render 'form' %>

<%= link_to 'Back', concepts_path %>

app/views/concepts/show.html.erb
<%= link_to 'back', root_path, class: 'btn btn-primary btn-lg' %>


<%= link_to 'new tip', new_concept_tip_path(@concept), class: 'btn btn-success btn-lg', id: 'new-tip-btn'%><br>


<div class="container-fluid">
  <div class="row-fluid">
    <div class="col-md-4 col-md-10 col-md-offset-2">
        <div class="concept_title thumb <%= @concept.concept %>">
            <h1><center><div class=""><%= @concept.concept %></div></center></h1>
          </div>
    </div>
  </div>
  <div class="col-md-10 col-md-offset-2">
  <% @tips.each do | tip | %>
        <div class="tab-pane fade active in">
          <h2><%= tip.title %></h2>
        </div>
  <ul class="nav nav-tabs">
    <li class="active"><a href="#problem-<%= tip.id %>" data-toggle="tab">problem</a></li>
    <li><a href="#error-<%= tip.id %>" data-toggle="tab">error</a></li>
    <li><a href="#solution-<%= tip.id %>" data-toggle="tab">solution</a></li>
    <li class="created-by">created by <%= tip.user.name %>!</li>

  </ul>
  <div id="myTabContent" class="tab-content">
    <div class="tab-pane fade active in" id="problem-<%= tip.id %>">
      <p><%= raw GitHub::Markdown.render(tip.problem).html_safe %></p>
    </div>
    <div class="tab-pane fade" id="error-<%= tip.id %>">
      <p><%= raw GitHub::Markdown.render(tip.error).html_safe %></p>
    </div>
    <div class="tab-pane fade" id="solution-<%= tip.id %>">
      <p><%= raw GitHub::Markdown.render(tip.solution).html_safe %></p>
    </div>
  </div>
  <% end %>
  </div>
</div>