config/routes.rb
Rails.application.routes.draw do
  root 'concepts#home'

  resources :concepts do
    resources :tips
  end
  resources :votes

  post 'signup', to: 'session#signup'
  post 'signin', to: 'session#signin'
  delete 'signout', to: 'session#signout'

end

app/models/tip.rb
# == Schema Information
#
# Table name: tips
#
#  id         :integer          not null, primary key
#  problem    :string(255)
#  error      :string(255)
#  solution   :string(255)
#  created_at :datetime
#  updated_at :datetime
#  concept_id :integer
#  user_id    :integer
#  title      :string(255)
#

class Tip < ActiveRecord::Base
  belongs_to :concept
  belongs_to :user
  has_many :votes

  def total_score
    votes.sum(:score)
  end

  mount_uploader :attachment, AttachmentUploader


end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  before_action :set_tip, only: [:show, :edit, :update, :destroy]
  before_action :set_concept, only: [:index, :new, :show, :create, :edit, :update, :destroy]

  # GET /tips
  # GET /tips.json
  def index
    @tips = Tip.all
  end

  # GET /tips/1
  # GET /tips/1.json
  def show
  end

  # GET /tips/new
  def new
    @tip = Tip.new
  end

  # GET /tips/1/edit
  def edit
  end

  # POST /tips
  # POST /tips.json
  def create
    @tip = Tip.new(tip_params)
    @tip.concept = @concept
    @tip.user = @current_user

    respond_to do |format|
      if @tip.save
        format.html { redirect_to concept_path(@concept) }
        format.json { render :show, status: :created, location: @tip }
      else
        format.html { render :new }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tips/1
  # PATCH/PUT /tips/1.json
  def update
    respond_to do |format|
      if @tip.update(tip_params)
        format.html { redirect_to concept_tip_path(@concept, @tip), notice: 'Tip was successfully updated.' }
        format.json { render :show, status: :ok, location: @tip }
      else
        format.html { render :edit }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tips/1
  # DELETE /tips/1.json
  def destroy
    @tip.destroy
    respond_to do |format|
      format.html { redirect_to concept_tip_url(@concept, @tip), notice: 'Tip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tip
      @tip = Tip.find(params[:id])
    end

    def set_concept
      @concept = Concept.find(params[:concept_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tip_params
      params.require(:tip).permit(:error, :problem, :solution, :title )
    end
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/views/tips/_form.html.erb
<%= form_for [@concept, @tip] do |f| %>

    <fieldset id="form-body">
      <div class="form-group">
        <label for="textArea" class="col-xs-4"><h3>title</h3></label>
        <div class="col-lg-12">
          <%= f.text_area 'title', class: 'form-control', rows: '1', placeholder: 'here is where your great title goes'  %>
<br><br>
        </div>
      </div>
      <div class="form-group">
        <label for="textArea" class="col-xs-4"><h3>problem</h3></label>
        <div class="col-lg-12">
          <%= f.text_area 'problem', class: 'form-control', rows: '3', placeholder: 'here is where your question, problem or issue goes.  Links, text or even code with ````  code between  ````'  %>
<br><br>
        </div>
      </div>
      <div class="form-group">
        <label for="textArea" class="col-xs-4"><h3>error</h3></label>
        <div class="col-lg-12">
          <%= f.text_area 'error', class: 'form-control', rows: '3', placeholder: 'if you have any errors that you can share then here is where they go'  %>
<br><br>
        </div>
      </div>
      <div class="form-group">
        <label for="textArea" class="col-xs-4"><h3>solution</h3></label>
        <div class="col-lg-12">
          <%= f.text_area 'solution', class: 'form-control', rows: '3', placeholder: 'finally!  the solution goes here.'  %>
<br><br>
        </div>
      </div>
      <% if @tip.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@tip.errors.count, "error") %> prohibited this tip from being saved:</h2>

            <ul>
              <% @tip.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group">
        <div class="col-lg-10 col-lg-offset-2">
          <%= f.submit 'submit', type: 'submit', class: 'btn btn-primary btn-lg'     %>
        </div>
      </div>
    </fieldset>

<% end %>

app/views/tips/edit.html.erb
<h1>Editing tip</h1>

<%= render 'form' %>

app/views/tips/index.html.erb
<h1>Listing tips</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tips.each do |tip| %>
      <tr>
        <td><%= link_to 'Show', tip %></td>
        <td><%= link_to 'Edit', edit_tip_path(tip) %></td>
        <td><%= link_to 'Destroy', tip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tip', new_concept_tip_path(@concept) %>

app/views/tips/new.html.erb
<%= link_to 'back', concept_path(@concept), class: 'btn btn-primary btn-lg' %>


<div class="container-fluid">
  <div class="row-fluid">
    <div class="col-md-4 col-md-10 col-md-offset-2">
      <div class="concept_title thumb <%= @concept.concept %>">
        <h1><center><div class="heading">new tip for <%= @concept.concept %></div></center></h1>
        <div class="col-md-10 col-md-offset--1">
          <%= render 'form' %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/tips/show.html.erb
<p id="notice"><%= notice %></p>



<%= link_to 'Edit', edit_concept_tip_path(@concept, @tip) %> |
<%= link_to 'Back', concept_path(@concept) %>