config/routes.rb
Rails.application.routes.draw do
  root 'concepts#home'

  resources :concepts do
    resources :tips
  end
  resources :votes

  post 'signup', to: 'session#signup'
  post 'signin', to: 'session#signin'
  delete 'signout', to: 'session#signout'

end

app/views/layouts/_flash_messages.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success alert-dismissible"><%= flash[:notice] %></div>
<% end %>
<% if flash[:error] %>
    <div class="alert alert-danger alert-dismissible"><%= flash[:error] %></div>
<% end %>
<% if flash[:warning] %>
    <div class="alert alert-warning alert-dismissible"><%= flash[:warning] %></div>
<% end %>

app/views/layouts/_signup_signin.html.erb
<!-- Button trigger modal -->


<!-- Modal -->
<div class="modal fade bs-modal-sm" id="myModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <br>
      <div class="bs-example bs-example-tabs">
        <ul id="myTab" class="nav nav-tabs">
          <li class="active"><a href="#signin" data-toggle="tab">Sign In</a></li>
          <li class=""><a href="#signup" data-toggle="tab">Sign Up</a></li>
          <li class=""><a href="#why" data-toggle="tab">Why?</a></li>
        </ul>
      </div>
      <div class="modal-body">
        <div id="myTabContent" class="tab-content">
          <div class="tab-pane fade in" id="why">
            <p>We need this information so that you can receive access to the site and its content. Rest assured your information will not be sold, traded, or given to anyone.</p>
            <p></p><br> Please contact <a mailto:href="JoeSixPack@Sixpacksrus.com"></a>JoeSixPack@Sixpacksrus.com</a> for any other inquiries.</p>
          </div>
          <div class="tab-pane fade active in" id="signin">
            <!--<form class="form-horizontal">-->
            <fieldset>
              <!-- Sign In Form -->
              <!-- Text input-->
              <div class="control-group">
                <%= form_tag signin_path, class: 'form-inline' do %>
                    <br>
                    <div class="controls">
                      <%= text_field_tag 'email', nil, class: 'form-control', type: 'text', placeholder: 'Enter your email', class: 'input-large', :require => true, :autofocus => true %>
                    </div>
                    </div>
                    <!-- Password input-->
                    <div class="control-group">
                      <br>
                      <div class="controls">
                        <%= password_field_tag 'password', nil, class: 'form-control', placeholder: 'Password', class: 'input-large', :require => true %>
                      </div>
                    </div>
                    <!-- Multiple Checkboxes (inline) -->
                    <div class="control-group">
                      <br>
                      <div class="controls">
                        <%= check_box_tag 'checkbox', 'yes', false %>Remember me
                        <!--Remember me-->
                        </label>
                      </div>
                      <br>
                    </div>
                    <!-- Button -->
                    <div class="control-group">
                      <div class="controls">
                        <%= submit_tag 'Sign in', class: 'btn btn-success' %>
                <% end %>
                </div>
                </div>
                </fieldset>
            <!--</form>-->
          </div>
          <div class="tab-pane fade" id="signup">
            <!--<form class="form-horizontal">-->
            <fieldset>
              <!-- Sign Up Form -->
              <!-- Text input-->
              <div class="control-group">
                <%= form_tag signup_path, class: 'form-signup', role: 'form'  do %>
                    <br>
                    <div class="controls">
                      <!--<input id="Email" name="Email" class="form-control" type="text" placeholder="JoeSixpack@sixpacksrus.com" class="input-large" required="">-->
                      <%= text_field_tag 'email', nil, class: 'form-control', type: 'text', placeholder: 'Email Address', class: 'input-large', :required => true %>
                    </div>
                    </div>
                    <!-- Text input-->
                    <div class="control-group">
                      <br>
                      <div class="controls">
                        <%= text_field_tag 'name', nil, class: 'form-control', placeholder: 'Name', class: 'input-large', :required => true, :autofocus => true %>
                      </div>
                    </div>
                    <!-- Password input-->
                    <div class="control-group">
                      <br>
                      <div class="controls">
                        <%= password_field_tag 'password', nil, class: 'form-control', placeholder: 'Password', class: 'input-large', :required => true %>
                        <!--<em>1-8 Characters</em>-->
                      </div>
                    </div>
                    <!-- Text input-->
                    <div class="control-group">
                      <br>
                      <div class="controls">
                        <%= password_field_tag 'password_confirmation', nil, class: 'form-control', placeholder: 'Confirm Password', class: 'input-large', :required => true %>
                      </div>
                    </div>
                    <!-- Multiple Radios (inline) -->
                    <br>
                    <div class="control-group">
                      <br>
                      <div class="controls">
                        <%= submit_tag 'Sign Up', class: 'btn btn-lg btn-primary btn-block' %>

                      </div>
                    </div>
                    </fieldset>
                    <!--</form>-->
                    </div>
                    </div>
                    </div>
                <% end %>
                <div class="modal-footer">
                  <center>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  </center>
                </div>
                </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Learnatizer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.0/superhero/bootstrap.min.css">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

</head>

<body>

<div class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to 'learnatizer', root_path, class: 'navbar-brand' %>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav navbar-right">
      <!--<li><a href="#">use badges for points 24</a></li>-->

      <li><div class="btn-toolbar">
        <div class="btn-group">
          <div class="btn-group">

            <% if signed_in? %>
                <%= submit_tag current_user.name, class: 'btn btn-success dropdown-toggle', data: {toggle:  'dropdown'} %>
            <% else %>
                <button class="btn btn-default" href="#signup" data-toggle="modal" style="float: right;" data-target="#myModal">Sign In</button>
            <% end %>

            <ul class="dropdown-menu">
              <li><%= link_to 'Sign out', signout_path, method: :delete%></li>
            </ul>
          </div>
        </div>
      </div></li>

    </ul>
  </div>
</div>
<%= render 'layouts/flash_messages' %>

   <%= yield %>

<%= render 'layouts/signup_signin' %>



</body>
</html>